@include('includes.classes.partials.steps-horizontal')
@include('includes.classes.partials.map-states-legend')
@include('includes.classes.partials.who-for')
@include('includes.home.reviews')
@include('includes.classes.partials.expected')
@include('includes.classes.partials.philosophy')
@include('includes.classes.partials.how-much')